# antioch
# Copyright (c) 1999-2012 Phil Christensen
#
#
# See LICENSE for details

"""
A highly-customizable, scalable game server for creating virtual worlds.
"""

from zope import interface

from twisted.python import versions

from antioch import conf
conf.init()

from antioch.client import DebugLoggingWSGIHandler

version = versions.Version('antioch', 2, 0, 0)
__version__ = version.short()

wsgi_handler = DebugLoggingWSGIHandler()

class IPlugin(interface.Interface):
	name = interface.Attribute('Name of this module.')
	script_url = interface.Attribute('Plugin script URL.')
	transaction_child = interface.Attribute('ampoule transaction child class.')
	
	def get_environment(self):
		"""
		Return a dict of items to add to the verb environment.
		"""
	
	def handle_message(self, msg):
		"""
		Handle a message generated by the verb environment.
		"""
	
	def get_commands(self):
		"""
		Return a dict of WorldTransaction/amp.Command classes provided by this module.
		"""
