# antioch
# Copyright (c) 1999-2011 Phil Christensen
#
#
# See LICENSE for details

"""
A highly-customizable, scalable game server for creating virtual worlds.
"""

from zope import interface

class IPlugin(interface.Interface):
	name = interface.Attribute('Name of this module.')
	script_url = interface.Attribute('Plugin script URL.')
	
	def get_environment(self):
		"""
		Return a dict of items to add to the verb environment.
		"""
	
	def handle_message(self, msg):
		"""
		Handle a message generated by the verb environment.
		"""
	
	def get_commands(self):
		"""
		Return a dict of WorldTransaction/amp.Command classes provided by this module.
		"""
