from zope import interface

class IModule(interface.Interface):
	name = interface.Attribute('Name of this module.')
	script_url = interface.Attribute('Plugin script URL.')
	
	def get_environment(self):
		"""
		Return a dict of items to add to the verb environment.
		"""
	
	def get_resource(self, user):
		"""
		Return the instantiated resource for this plugin.
		"""
	
	def handle_message(self, msg):
		"""
		Handle a message generated by the verb environment.
		"""
	
	def get_commands(self):
		"""
		Return a dict of WorldTransaction/amp.Command classes provided by this module.
		"""
	
	def activate_client_commands(self, client):
		"""
		Given the athena.LiveElement instance, install the available command support.
		"""
