# antioch
# Copyright (c) 1999-2018 Phil Christensen
#
#
# See LICENSE for details

"""
Core functionality.
"""
from zope.interface import provider

from antioch import IPlugin

@provider(IPlugin)
class CorePlugin(object):
    name = 'core'
    script_url = ''
    
    def get_environment(self):
        """
        Return a dict of items to add to the verb environment.
        """
        return dict()
    
    def handle_message(self, msg):
        """
        Handle a message generated by the verb environment.
        """