# antioch
# Copyright (c) 1999-2016 1999-2012 Phil Christensen
#
#
# See LICENSE for details

"""
Core functionality.
"""
from zope.interface import classProvides

from antioch import IPlugin

class CorePlugin(object):
	classProvides(IPlugin)
	
	name = u'core'
	script_url = u''
	
	def get_environment(self):
		"""
		Return a dict of items to add to the verb environment.
		"""
		return dict()
	
	def handle_message(self, msg):
		"""
		Handle a message generated by the verb environment.
		"""