# Generated by Django 2.1.1 on 2018-09-08 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredPlayer',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Player')),
                ('email', models.CharField(max_length=255)),
                ('activation_key', models.CharField(max_length=255)),
            ],
            bases=('core.player',),
        ),
    ]
