# antioch
# Copyright (c) 1999-2011 Phil Christensen
#
#
# See LICENSE for details

"""
Core functionality.
"""
from zope.interface import classProvides

from twisted import plugin

from antioch import modules
from antioch.core import transact

class CoreModule(object):
	classProvides(plugin.IPlugin, modules.IModule)
	
	name = u'core'
	script_url = u'' #u'/plugin/editor/assets/js/editor-plugin.js'
	
	def get_environment(self):
		"""
		Return a dict of items to add to the verb environment.
		"""
		return dict()
	
	def get_resource(self, user):
		"""
		Return the instantiated resource for this plugin.
		"""
		return None
	
	def handle_message(self, msg):
		"""
		Handle a message generated by the verb environment.
		"""
	
	def get_commands(self):
		"""
		Return a dict of WorldTransaction/amp.Command classes provided by this module.
		"""
		from antioch.core import transact
		from antioch.modules import discover_commands
		return discover_commands(transact)
	
	def activate_client_commands(self, client):
		"""
		Given the athena.LiveElement instance, install the available command support.
		"""