# antioch
# Copyright (c) 1999-2011 Phil Christensen
#
#
# See LICENSE for details

"""
Core functionality.
"""
from zope.interface import classProvides

from twisted import plugin

from antioch import module
from antioch.core import transact

class CoreModule(object):
	classProvides(plugin.IPlugin, module.IModule)
	
	name = u'core'
	script_url = u''
	
	def get_environment(self):
		"""
		Return a dict of items to add to the verb environment.
		"""
		return dict()
	
	def handle_message(self, msg):
		"""
		Handle a message generated by the verb environment.
		"""
	
	def get_commands(self):
		"""
		Return a dict of WorldTransaction/amp.Command classes provided by this module.
		"""
		from antioch.core import transact
		from antioch.modules import discover_commands
		return discover_commands(transact)
