# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(choices=[(b'allow', b'allow'), (b'deny', b'deny')], max_length=5)),
                ('type', models.CharField(choices=[(b'accessor', b'accessor'), (b'group', b'group')], max_length=8)),
                ('group', models.CharField(choices=[(b'everyone', b'everyone'), (b'owners', b'owners'), (b'wizards', b'wizards')], max_length=8, null=True)),
                ('weight', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'access',
                'verbose_name_plural': 'access controls',
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'object_alias',
                'verbose_name_plural': 'aliases',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unique_name', models.BooleanField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='core.Object')),
            ],
            options={
                'db_table': 'object',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer', to='core.Object')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='core.Object')),
            ],
            options={
                'db_table': 'object_observer',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, null=True)),
                ('wizard', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('crypt', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(null=True)),
                ('last_logout', models.DateTimeField(null=True)),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Object')),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[(b'string', b'string'), (b'python', b'python'), (b'dynamic', b'dynamic')], max_length=255)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.Object')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Object')),
            ],
            options={
                'db_table': 'property',
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='core.Object')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='core.Object')),
            ],
            options={
                'db_table': 'object_relation',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb_name', models.CharField(max_length=255)),
                ('args', models.TextField()),
                ('kwargs', models.TextField()),
                ('created', models.DateTimeField()),
                ('delay', models.IntegerField()),
                ('killed', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('trace', models.TextField(blank=True, null=True)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.Object')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('ability', models.BooleanField()),
                ('method', models.BooleanField()),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbs', to='core.Object')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Object')),
            ],
            options={
                'db_table': 'verb',
            },
        ),
        migrations.CreateModel(
            name='VerbName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='core.Verb')),
            ],
            options={
                'db_table': 'verb_name',
            },
        ),
        migrations.AddField(
            model_name='object',
            name='observers',
            field=models.ManyToManyField(related_name='observing', through='core.Observation', to='core.Object'),
        ),
        migrations.AddField(
            model_name='object',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Object'),
        ),
        migrations.AddField(
            model_name='object',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='core.Relationship', to='core.Object'),
        ),
        migrations.AddField(
            model_name='alias',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.Object'),
        ),
        migrations.AddField(
            model_name='access',
            name='accessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='core.Object'),
        ),
        migrations.AddField(
            model_name='access',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acl', to='core.Object'),
        ),
        migrations.AddField(
            model_name='access',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='core.Permission'),
        ),
        migrations.AddField(
            model_name='access',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acl', to='core.Property'),
        ),
        migrations.AddField(
            model_name='access',
            name='verb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acl', to='core.Verb'),
        ),
    ]
