# Generated by Django 2.1.8 on 2019-05-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('child', 'parent')},
        ),
    ]
