# Generated by Django 2.1.8 on 2019-06-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190506_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='core.Object'),
        ),
        migrations.AlterField(
            model_name='object',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Object'),
        ),
    ]
