# Generated by Django 2.1.10 on 2019-07-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190721_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
