AWSTemplateFormatVersion: "2010-09-09"
Description: antioch deployment infrastructure
Parameters:
  Name:
    Type: String
    Default: antioch
    Description: Name of this application
  Environment:
    Type: String
    Default: prod
    Description: Name of this environment
  ImageTag:
    Type: String
    Default: latest
    Description: The Docker image tag to use for this deployment.
  CostAllocationTagKey:
    Type: String
    Default: BillingGroup
    Description: The AWS tag key to add to all billable resources.
  CostAllocationTagValue:
    Type: String
    Default: antioch-prod
    Description: The AWS tag value to add to all billable resources.
  DBMasterPasswordSsmParamName:
    Type: String
    Default: /antioch/prod/db-password
    Description: Master password for the DB instance.
  DBMasterPasswordSsmParamVersion:
    Type: Number
    Default: 2
    Description: Master password for the DB instance.
Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/antioch-prod-cfn/aws-vpc.template
      Parameters:
        AvailabilityZones: !Join [",", [
          !Select [ 0, !GetAZs "" ],
          !Select [ 1, !GetAZs "" ],
          !Select [ 2, !GetAZs "" ]
        ]]
        CreateHighAvailabilityNATs: false
        NumberOfAZs: 3
        VPCCIDR: 10.42.0.0/21
        PublicSubnet1CIDR: 10.42.0.0/24
        PublicSubnet2CIDR: 10.42.1.0/24
        PublicSubnet3CIDR: 10.42.2.0/24
        PublicSubnetTag1: !Join ["", ["Name=", !Ref "Name", "-", !Ref "Environment", "-public"]]
        PublicSubnetTag2: !Join ["=", [!Ref "CostAllocationTagKey", !Ref "CostAllocationTagValue"]]
        PrivateSubnet1ACIDR: 10.42.3.0/24
        PrivateSubnet2ACIDR: 10.42.4.0/24
        PrivateSubnet3ACIDR: 10.42.5.0/24
        PrivateSubnetATag1: !Join ["", ["Name=", !Ref "Name", "-", !Ref "Environment", "-private"]]
        PrivateSubnetATag2: !Join ["=", [!Ref "CostAllocationTagKey", !Ref "CostAllocationTagValue"]]
  namespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: antioch.local
      Description: Internal namespace for antioch service discovery.
      Vpc: !GetAtt "vpc.Outputs.VPCID"
  cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ["-", [!Ref "Name", !Ref "Environment"]]
  containerExecutionRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "ecs-tasks.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Path: /
      RoleName: !Join ["-", [!Ref "Name", !Ref "Environment", "exec-role"]]
  taskRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "ecs-tasks.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      Policies:
        - PolicyName: ssm-param-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "ssm:GetParametersByPath"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Name}/${Environment}"
      Path: /
      RoleName: !Join ["-", [!Ref "Name", !Ref "Environment", "task-role"]]
  webappSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: antioch webapp security group
      GroupName: !Join ["-", [!Ref "Name", !Ref "Environment", "webapp-sg"]]
      VpcId: !GetAtt "vpc.Outputs.VPCID"
  staticBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
        - AllowedMethods: ["GET"]
          AllowedOrigins: ["*"]
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: !Ref "CostAllocationTagKey"
          Value: !Ref "CostAllocationTagValue"
  staticAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: static-web-assets
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub  'arn:aws:s3:::${staticBucket}/*'
      Bucket: !Ref staticBucket
  redisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: antioch Redis security group
      GroupName: !Join ["-", [!Ref "Name", !Ref "Environment", "redis-sg"]]
      SecurityGroupIngress:
        - Description: worker and beat
          FromPort: 6379
          IpProtocol: tcp
          SourceSecurityGroupId: !Ref "workerSecurityGroup"
          ToPort: 6379
        - Description: webapp on API Gateway
          FromPort: 6379
          IpProtocol: tcp
          SourceSecurityGroupId: !Ref "webappSecurityGroup"
          ToPort: 6379
      VpcId: !GetAtt "vpc.Outputs.VPCID"
  redisTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: redis
          Image: redis
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-region: !Ref "AWS::Region"
              awslogs-group: !Join ["/", ["/aws/ecs", !Ref "cluster", "redis"]]
              awslogs-stream-prefix: redis
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities: ["FARGATE"]
      ExecutionRoleArn: !Ref "containerExecutionRole"
  redisDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: !Join ["-", [!Ref "Environment", "redis"]]
      Description: Service discovery for antioch Redis
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 300
      HealthCheckCustomConfig:
        FailureThreshold: 1
      NamespaceId: !Ref namespace
  redisService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref "cluster"
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref "redisSecurityGroup"
          Subnets:
            - !GetAtt "vpc.Outputs.PrivateSubnet1AID"
            - !GetAtt "vpc.Outputs.PrivateSubnet2AID"
            - !GetAtt "vpc.Outputs.PrivateSubnet3AID"
      ServiceRegistries:
        - RegistryArn: !GetAtt redisDiscovery.Arn
      TaskDefinition: !Ref redisTask
  workerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: antioch worker security group
      GroupName: !Join ["-", [!Ref "Name", !Ref "Environment", "worker-sg"]]
      VpcId: !GetAtt "vpc.Outputs.VPCID"
  workerTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: worker
          Image: !Join [":", ["philchristensen/antioch", !Ref "ImageTag"]]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-region: !Ref "AWS::Region"
              awslogs-group: !Join ["/", ["/aws/ecs", !Ref "cluster", "worker"]]
              awslogs-stream-prefix: !Ref "ImageTag"
          Environment:
            - Name: ROLE
              Value: worker
            - Name: DJANGO_SETTINGS_MODULE
              Value: !Join [".", ["antioch.settings", !Ref "Environment"]]
            - Name: DB_HOST
              Value: !GetAtt database.Endpoint.Address
            - Name: DB_PORT
              Value: !GetAtt database.Endpoint.Port
            - Name: STATIC_BUCKET
              Value: !Ref staticBucket
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities: ["FARGATE"]
      ExecutionRoleArn: !Ref "containerExecutionRole"
      TaskRoleArn: !Ref "taskRole"
  workerService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref "cluster"
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref "workerSecurityGroup"
          Subnets:
            - !GetAtt "vpc.Outputs.PrivateSubnet1AID"
            - !GetAtt "vpc.Outputs.PrivateSubnet2AID"
            - !GetAtt "vpc.Outputs.PrivateSubnet3AID"
      TaskDefinition: !Ref workerTask
  beatTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: beat
          Image: !Join [":", ["philchristensen/antioch", !Ref "ImageTag"]]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-region: !Ref "AWS::Region"
              awslogs-group: !Join ["/", ["/aws/ecs", !Ref "cluster", "beat"]]
              awslogs-stream-prefix: !Ref "ImageTag"
          Environment:
            - Name: ROLE
              Value: beat
            - Name: DJANGO_SETTINGS_MODULE
              Value: !Join [".", ["antioch.settings", !Ref "Environment"]]
            - Name: DB_HOST
              Value: !GetAtt database.Endpoint.Address
            - Name: DB_PORT
              Value: !GetAtt database.Endpoint.Port
            - Name: STATIC_BUCKET
              Value: !Ref staticBucket
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities: ["FARGATE"]
      ExecutionRoleArn: !Ref "containerExecutionRole"
      TaskRoleArn: !Ref "taskRole"
  beatService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref "cluster"
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref "workerSecurityGroup"
          Subnets:
            - !GetAtt "vpc.Outputs.PrivateSubnet1AID"
            - !GetAtt "vpc.Outputs.PrivateSubnet2AID"
            - !GetAtt "vpc.Outputs.PrivateSubnet3AID"
      TaskDefinition: !Ref beatTask
  databaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: antioch database security group
      GroupName: !Join ["-", [!Ref "Name", !Ref "Environment", "db-sg"]]
      SecurityGroupIngress:
        - Description: worker and beat
          FromPort: 3306
          IpProtocol: tcp
          SourceSecurityGroupId: !Ref "workerSecurityGroup"
          ToPort: 3306
        - Description: webapp on API Gateway
          FromPort: 3306
          IpProtocol: tcp
          SourceSecurityGroupId: !Ref "webappSecurityGroup"
          ToPort: 3306
      VpcId: !GetAtt "vpc.Outputs.VPCID"
  databaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: antioch database subnet group
      DBSubnetGroupName: !Join ["-", [!Ref "Name", !Ref "Environment", "dbsubnetgroup"]]
      SubnetIds:
        - !GetAtt "vpc.Outputs.PrivateSubnet1AID"
        - !GetAtt "vpc.Outputs.PrivateSubnet2AID"
        - !GetAtt "vpc.Outputs.PrivateSubnet3AID"
  database:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: !Ref "databaseSubnetGroup"
      DBName: antioch
      EnableCloudwatchLogsExports: ["audit","error","general","slowquery"]
      Engine: mysql
      EngineVersion: "5.7"
      MasterUsername: antioch
      MasterUserPassword: !Sub "{{resolve:ssm-secure:${DBMasterPasswordSsmParamName}:${DBMasterPasswordSsmParamVersion}}}"
      MultiAZ: false
      PubliclyAccessible: false
      StorageEncrypted: false
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref "databaseSecurityGroup"
      Tags:
        - Key: !Ref "CostAllocationTagKey"
          Value: !Ref "CostAllocationTagValue"
Outputs:
  DatabaseHost:
    Description: The hostname of the created database
    Value: !GetAtt database.Endpoint.Address
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "database-host" ] ]
  DatabasePort:
    Description: The port of the created database
    Value: !GetAtt database.Endpoint.Port
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "databse-port" ] ]
  PrivateSubnet1AID:
    Value: !GetAtt vpc.Outputs.PrivateSubnet1AID
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "subnet-private-1" ] ]
  PrivateSubnet2AID:
    Value: !GetAtt vpc.Outputs.PrivateSubnet2AID
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "subnet-private-2" ] ]
  PrivateSubnet3AID:
    Value: !GetAtt vpc.Outputs.PrivateSubnet3AID
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "subnet-private-3" ] ]
  WebappSecurityGroup:
    Value: !Ref webappSecurityGroup
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "webapp-sg" ] ]
  BeatServiceName:
    Value: !GetAtt beatService.Name
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "beat-service" ] ]
  RedisServiceName:
    Value: !GetAtt redisService.Name
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "redis-service" ] ]
  WorkerServiceName:
    Value: !GetAtt workerService.Name
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "worker-service" ] ]
  StaticBucketName:
    Value: !Ref staticBucket
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "static-bucket" ] ]
