name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source...
      uses: actions/checkout@v1
    - name: Setup Python...
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Setup Pipenv...
      uses: dschep/install-pipenv-action@v1
    - name: Install development headers...
      run: sudo apt-get install libmysqlclient-dev libreadline-dev libncurses-dev
    - name: Install Python dependencies...
      run: pipenv install --dev
    - name: Run unit tests...
      env:
        DJANGO_SETTINGS_MODULE: antioch.settings.unittests
      run: pipenv run python manage.py test --keepdb
